"""user updated

Revision ID: 407e3cc65fff
Revises: dc2778fec00f
Create Date: 2023-12-16 18:33:41.969641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407e3cc65fff'
down_revision: Union[str, None] = 'dc2778fec00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('passcodes_user_id_fkey', 'passcodes', type_='foreignkey')
    op.create_foreign_key(None, 'passcodes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passcodes', type_='foreignkey')
    op.create_foreign_key('passcodes_user_id_fkey', 'passcodes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
